annotations: /home/Waste-Detector/data/mixed_annotations.json
indices: /home/Waste-Detector/data/indices.json
img_dir: /home/
checkpoint_path: /home/checkpoints
checkpoint_name: detr_icevision
warm_up: False