annotations:
- [mju-waste-v1.0/fixed_train.json, /home/mju-waste/JPEGImages, False]
- [mju-waste-v1.0/fixed_val.json, /home/mju-waste/JPEGImages, False]
- [mju-waste-v1.0/fixed_test.json, /home/mju-waste/JPEGImages, False]
- [TACO-master/data/annotations.json, /home/data, False]
- [background-dataset/background_annotations.json, /home/background_dataset/images, True]
filename: mixed_annotations.json
