TACO_REPLACEMENTS = {
    'Foam food container': 'plastic',
    'Squeezable tube': 'plastic',
    'Metal lid': 'plastic',
    'Egg carton': 'carton',
    'Spread tub': 'plastic',
    'Paper bag': 'plastic',
    'Normal paper': 'carton',
    'Tissues': 'rest',
    'Plastic straw': 'plastic',
    'Single-use carrier bag': 'plastic',
    'Scrap metal': 'other',
    'Crisp packet': 'plastic',
    'Styrofoam piece': 'carton',
    'Glass bottle': 'glass',
    'Drink can': 'plastic',
    'Other plastic cup': 'plastic',
    'Battery': 'dangerous',
    'Paper cup': 'carton',
    'Polypropylene bag': 'plastic',
    'Rope & strings': 'rest',
    'Food Can': 'plastic',
    'Plastic lid': 'plastic',
    'Wrapping paper': 'carton',
    'Clear plastic bottle': 'plastic',
    'Other plastic wrapper': 'plastic',
    'Carded blister pack': 'carton',
    'Corrugated carton': 'carton',
    'Foam cup': 'plastic',
    'Magazine paper': 'carton',
    'Broken glass': 'glass',
    'Paper straw': 'carton',
    'Other plastic bottle': 'plastic',
    'Metal bottle cap': 'glass',
    'Unlabelled litter': 'other',
    'Garbage bag': 'rest',
    'Plastic bottle cap': 'plastic',
    'Shoe': 'rest',
    'Other plastic': 'plastic',
    'Plastified paper bag': 'plastic',
    'Tupperware': 'plastic',
    'Plastic glooves': 'plastic',
    'Six pack rings': 'plastic',
    'Glass cup': 'glass',
    'Disposable plastic cup': 'plastic',
    'Plastic film': 'plastic',
    'Pizza box': 'carton',
    'Meal carton': 'carton',
    'Plastic utensils': 'plastic',
    'Disposable food container': 'plastic',
    'Cigarette': 'rest',
    'Food waste': 'organic',
    'Other carton': 'carton',
    'Glass jar': 'glass',
    'Toilet tube': 'carton',
    'Other plastic container': 'plastic',
    'Pop tab': 'plastic',
    'Aluminium blister pack': 'plastic',
    'Aerosol': 'plastic',
    'Aluminium foil': 'plastic',
    'Drink carton': 'carton',
    'Unlabeled litter': 'other'
}