version: '3'
services:
  frontend:
      build:
          context: .
          dockerfile: frontend.Dockerfile
      image: 903243951329.dkr.ecr.eu-west-1.amazonaws.com/frontend:latest 
      ports:
          - "8501:8501"
      logging:
          driver: awslogs
          options: 
              awslogs-group: tutorial
              awslogs-region: eu-west-1
              awslogs-stream-prefix: web
      command: python3 -m deployment.frontend
  backend:
      build:
          context: .
          dockerfile: backend.Dockerfile
      image: 903243951329.dkr.ecr.eu-west-1.amazonaws.com/backend:latest 
      ports:
          - "5000:5000"
      logging:
          driver: awslogs
          options:
              awslogs-group: tutorial
              awslogs-region: eu-west-1
              awslogs-stream-prefix: web
      command: python3 -m uvicorn deployment.backend:app --host 0.0.0.0 --port 5000
      #traefik: # new
      #  image: traefik:v2.2
      #  #ports:
      #  #    - 8008:80
      #  #    - 8081:8080
      #  volumes:
      #    - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      #    - "/var/run/docker.sock:/var/run/docker.sock:ro"
