annotations:
- [/home/mju-waste/cat_fixed_train.json, /home/mju-waste/JPEGImages]
- [/home/mju-waste/cat_fixed_val.json, /home/mju-waste/JPEGImages]
- [/home/mju-waste/cat_fixed_test.json, /home/mju-waste/JPEGImages]
- [/home/data/annotations.json, /home/data]
background_imgs_set: /home/background_dataset/fixed_background_df.csv
train_path: /home/mixed-dataset/mixed_train_7_class.pkl
val_path: /home/mixed-dataset/mixed_val_7_class.pkl
test_path: /home/mixed-dataset/mixed_test_7_class.pkl