annotations:
- [/Waste-Detector/data/mju/fixed_train.json, data/mju/JPEGImages]
- [/Waste-Detector/data/mju/fixed_val.json, data/mju/JPEGImages]
- [/Waste-Detector/data/mju/fixed_test.json, data/mju/JPEGImages]
- [/Waste-Detector/data/taco/annotations.json, data/taco]
background_imgs_set: /home/background_dataset/fixed_background_df.csv
train_path: /Waste-Detector/data/classification/train_7_class.pkl
val_path: /Waste-Detector/data/classification/val_7_class.pkl
test_path: /Waste-Detector/data/classification/test_7_class.pkl
