annotations:
- /home/mju-waste/fixed_train.json
- /home/mju-waste/fixed_val.json
- /home/mju-waste/fixed_test.json
imgs_path: /home/mju-waste/JPEGImages
background_imgs_set: /home/background_dataset/fixed_background_df.csv
train_path: /home/mju-waste/train_1_class.pkl
val_path: /home/mju-waste/val_1_class.pkl
test_path: /home/mju-waste/test_1_class.pkl