annotations:
- [/home/data/annotations.json, /home/data]
background_imgs_set: /home/background_dataset/fixed_background_df.csv
train_path: /home/data/train_1_class.pkl
val_path: /home/data/val_1_class.pkl
test_path: /home/data/test_1_class.pkl